version: '3'

services:
  web:
    build: .
    ports:
      - "4848:4848"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: keinos/sqlite3
    volumes:
      - ./data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge